name: NSCamp 2016
description: A weekend of hacking for iOS, macOS, tvOS & watchOS developers everywhere.
ticket_url: 'https://nscamp.herokuapp.com/rego'
#markdown: redcarpet
#highlighter: pygments
exclude: [Gemfile, Gemfile.lock, script, Rakefile]
# source: site
# destination: public
